// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(FlexiRoomsContext))]
    [Migration("20260829222530_FK_Hotel_user")]
    partial class FK_Hotel_user
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCity")
                        .HasColumnType("integer");

                    b.Property<string>("Latitud")
                        .HasColumnType("text");

                    b.Property<string>("Longitud")
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdCity = 1,
                            Latitud = "-34.6037",
                            Longitud = "-58.3816",
                            Number = "1234",
                            PostalCode = "C1043",
                            Street = "Av. Corrientes"
                        },
                        new
                        {
                            Id = 2,
                            IdCity = 23,
                            Latitud = "-32.9442",
                            Longitud = "-60.6505",
                            Number = "890",
                            PostalCode = "S2000",
                            Street = "Bv. Oroño"
                        },
                        new
                        {
                            Id = 3,
                            IdCity = 15,
                            Latitud = "-32.8895",
                            Longitud = "-68.8458",
                            Number = "456",
                            PostalCode = "M5500",
                            Street = "Av. San Martín"
                        },
                        new
                        {
                            Id = 4,
                            IdCity = 18,
                            Latitud = "-41.1335",
                            Longitud = "-71.3103",
                            Number = "11500",
                            PostalCode = "R8400",
                            Street = "Av. Bustillo"
                        },
                        new
                        {
                            Id = 5,
                            IdCity = 19,
                            Latitud = "-24.7829",
                            Longitud = "-65.4232",
                            Number = "786",
                            PostalCode = "A4400",
                            Street = "Caseros"
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("AccountActivate")
                        .HasColumnType("boolean");

                    b.Property<string>("CodeArea")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("text");

                    b.Property<bool>("IsOwnAccount")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ManagedHotelId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OwnedHotelIds")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("ProviderAccount")
                        .HasColumnType("boolean");

                    b.Property<string>("SecondName")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Models.Bookings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckInTimeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateReserved")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdRoom")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CheckInTimeId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Infrastructure.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Buenos Aires",
                            ProvinceId = 24
                        },
                        new
                        {
                            Id = 2,
                            Name = "La Plata",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mar del Plata",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bahía Blanca",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "San Fernando del Valle de Catamarca",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Resistencia",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 7,
                            Name = "Comodoro Rivadavia",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 8,
                            Name = "Córdoba",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 9,
                            Name = "Corrientes",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 10,
                            Name = "Paraná",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 11,
                            Name = "Formosa",
                            ProvinceId = 8
                        },
                        new
                        {
                            Id = 12,
                            Name = "San Salvador de Jujuy",
                            ProvinceId = 9
                        },
                        new
                        {
                            Id = 13,
                            Name = "Santa Rosa",
                            ProvinceId = 10
                        },
                        new
                        {
                            Id = 14,
                            Name = "La Rioja",
                            ProvinceId = 11
                        },
                        new
                        {
                            Id = 15,
                            Name = "Mendoza",
                            ProvinceId = 12
                        },
                        new
                        {
                            Id = 16,
                            Name = "Posadas",
                            ProvinceId = 13
                        },
                        new
                        {
                            Id = 17,
                            Name = "Neuquén",
                            ProvinceId = 14
                        },
                        new
                        {
                            Id = 18,
                            Name = "San Carlos de Bariloche",
                            ProvinceId = 15
                        },
                        new
                        {
                            Id = 19,
                            Name = "Salta",
                            ProvinceId = 16
                        },
                        new
                        {
                            Id = 20,
                            Name = "San Juan",
                            ProvinceId = 17
                        },
                        new
                        {
                            Id = 21,
                            Name = "San Luis",
                            ProvinceId = 18
                        },
                        new
                        {
                            Id = 22,
                            Name = "Río Gallegos",
                            ProvinceId = 19
                        },
                        new
                        {
                            Id = 23,
                            Name = "Rosario",
                            ProvinceId = 20
                        },
                        new
                        {
                            Id = 24,
                            Name = "Santa Fe",
                            ProvinceId = 20
                        },
                        new
                        {
                            Id = 25,
                            Name = "Santiago del Estero",
                            ProvinceId = 21
                        },
                        new
                        {
                            Id = 26,
                            Name = "Ushuaia",
                            ProvinceId = 22
                        },
                        new
                        {
                            Id = 27,
                            Name = "San Miguel de Tucumán",
                            ProvinceId = 23
                        },
                        new
                        {
                            Id = 28,
                            Name = "Puerto Iguazú",
                            ProvinceId = 13
                        },
                        new
                        {
                            Id = 29,
                            Name = "Villa Carlos Paz",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 30,
                            Name = "El Calafate",
                            ProvinceId = 19
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.Cost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostPerTime")
                        .HasColumnType("numeric");

                    b.Property<int>("Hour")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Costs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CostPerTime = 45000m,
                            Hour = 2
                        },
                        new
                        {
                            Id = 2,
                            CostPerTime = 78000m,
                            Hour = 4
                        },
                        new
                        {
                            Id = 3,
                            CostPerTime = 120000m,
                            Hour = 8
                        },
                        new
                        {
                            Id = 4,
                            CostPerTime = 165000m,
                            Hour = 12
                        },
                        new
                        {
                            Id = 5,
                            CostPerTime = 52000m,
                            Hour = 2
                        },
                        new
                        {
                            Id = 6,
                            CostPerTime = 86000m,
                            Hour = 4
                        },
                        new
                        {
                            Id = 7,
                            CostPerTime = 134000m,
                            Hour = 8
                        },
                        new
                        {
                            Id = 8,
                            CostPerTime = 182000m,
                            Hour = 12
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Brasil"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Uruguay"
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressHotelId")
                        .HasColumnType("integer");

                    b.Property<int>("CodeArea")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("text");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddressHotelId");

                    b.HasIndex("IdentityNumber");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressHotelId = 1,
                            CodeArea = 11,
                            Description = "Hotel urbano en el centro porteño.",
                            Email = "reservas@hotelobelisco.com",
                            MetaDescription = "Ideal para negocios y escapadas en Buenos Aires.",
                            Name = "Hotel Obelisco",
                            PhoneNumber = 43219876
                        },
                        new
                        {
                            Id = 2,
                            AddressHotelId = 2,
                            CodeArea = 341,
                            Description = "Hotel moderno con vista al río Paraná.",
                            Email = "hola@rosarioriverside.com",
                            MetaDescription = "Alojamiento premium en Rosario.",
                            Name = "Rosario Riverside",
                            PhoneNumber = 5588776
                        },
                        new
                        {
                            Id = 3,
                            AddressHotelId = 3,
                            CodeArea = 261,
                            Description = "Suites boutique cerca de bodegas y montaña.",
                            Email = "info@andessuites.com",
                            MetaDescription = "Descanso y vino en Mendoza.",
                            Name = "Andes Suites Mendoza",
                            PhoneNumber = 4477551
                        },
                        new
                        {
                            Id = 4,
                            AddressHotelId = 4,
                            CodeArea = 294,
                            Description = "Hotel de montaña con vista al lago.",
                            Email = "contacto@patagoniaview.com",
                            MetaDescription = "Experiencia patagónica en Bariloche.",
                            Name = "Patagonia View Bariloche",
                            PhoneNumber = 4522334
                        },
                        new
                        {
                            Id = 5,
                            AddressHotelId = 5,
                            CodeArea = 387,
                            Description = "Hotel cálido en el casco histórico salteño.",
                            Email = "reservas@saltacolonial.com",
                            MetaDescription = "Tradición y confort en Salta.",
                            Name = "Salta Colonial",
                            PhoneNumber = 4123456
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.HotelPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("HotelId")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("HotelPicture");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HotelId = 1,
                            Path = "assets/hotels/obelisco.jpg"
                        },
                        new
                        {
                            Id = 2,
                            HotelId = 2,
                            Path = "assets/hotels/rosario-riverside.jpg"
                        },
                        new
                        {
                            Id = 3,
                            HotelId = 3,
                            Path = "assets/hotels/andes-suites.jpg"
                        },
                        new
                        {
                            Id = 4,
                            HotelId = 4,
                            Path = "assets/hotels/patagonia-view.jpg"
                        },
                        new
                        {
                            Id = 5,
                            HotelId = 5,
                            Path = "assets/hotels/salta-colonial.jpg"
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.PreBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdRoom")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeToExpire")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int?>("UserId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId1");

                    b.ToTable("PreBooking");
                });

            modelBuilder.Entity("Infrastructure.Models.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Provincies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Buenos Aires"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Catamarca"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Name = "Chaco"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            Name = "Chubut"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            Name = "Córdoba"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 1,
                            Name = "Corrientes"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 1,
                            Name = "Entre Ríos"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 1,
                            Name = "Formosa"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 1,
                            Name = "Jujuy"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 1,
                            Name = "La Pampa"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 1,
                            Name = "La Rioja"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 1,
                            Name = "Mendoza"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 1,
                            Name = "Misiones"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 1,
                            Name = "Neuquén"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 1,
                            Name = "Río Negro"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 1,
                            Name = "Salta"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 1,
                            Name = "San Juan"
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 1,
                            Name = "San Luis"
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 1,
                            Name = "Santa Cruz"
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 1,
                            Name = "Santa Fe"
                        },
                        new
                        {
                            Id = 21,
                            CountryId = 1,
                            Name = "Santiago del Estero"
                        },
                        new
                        {
                            Id = 22,
                            CountryId = 1,
                            Name = "Tierra del Fuego"
                        },
                        new
                        {
                            Id = 23,
                            CountryId = 1,
                            Name = "Tucumán"
                        },
                        new
                        {
                            Id = 24,
                            CountryId = 1,
                            Name = "Ciudad Autónoma de Buenos Aires"
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AvialableNow")
                        .HasColumnType("boolean");

                    b.Property<int>("BedNumbers")
                        .HasColumnType("integer");

                    b.Property<int?>("CostId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("HotelsId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CostId");

                    b.HasIndex("HotelsId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvialableNow = true,
                            BedNumbers = 1,
                            CostId = 1,
                            Description = "Habitación individual con escritorio.",
                            HotelsId = 1,
                            Name = "Single Business"
                        },
                        new
                        {
                            Id = 2,
                            AvialableNow = true,
                            BedNumbers = 2,
                            CostId = 2,
                            Description = "Habitación doble con desayuno incluido.",
                            HotelsId = 1,
                            Name = "Doble Ejecutiva"
                        },
                        new
                        {
                            Id = 3,
                            AvialableNow = true,
                            BedNumbers = 2,
                            CostId = 6,
                            Description = "Suite con vista al río.",
                            HotelsId = 2,
                            Name = "Suite Paraná"
                        },
                        new
                        {
                            Id = 4,
                            AvialableNow = false,
                            BedNumbers = 3,
                            CostId = 7,
                            Description = "Ideal para familias y estadías cortas.",
                            HotelsId = 2,
                            Name = "Familiar Rosario"
                        },
                        new
                        {
                            Id = 5,
                            AvialableNow = true,
                            BedNumbers = 2,
                            CostId = 6,
                            Description = "Habitación premium con ambientación mendocina.",
                            HotelsId = 3,
                            Name = "Suite Malbec"
                        },
                        new
                        {
                            Id = 6,
                            AvialableNow = true,
                            BedNumbers = 4,
                            CostId = 8,
                            Description = "Amplia habitación para grupos pequeños.",
                            HotelsId = 3,
                            Name = "Familiar Cordillera"
                        },
                        new
                        {
                            Id = 7,
                            AvialableNow = true,
                            BedNumbers = 2,
                            CostId = 7,
                            Description = "Vista al lago y detalles patagónicos.",
                            HotelsId = 4,
                            Name = "Lago Superior"
                        },
                        new
                        {
                            Id = 8,
                            AvialableNow = true,
                            BedNumbers = 3,
                            CostId = 8,
                            Description = "Suite con living y balcón.",
                            HotelsId = 4,
                            Name = "Suite Nahuel"
                        },
                        new
                        {
                            Id = 9,
                            AvialableNow = true,
                            BedNumbers = 1,
                            CostId = 1,
                            Description = "Opción práctica para viajeros solos.",
                            HotelsId = 5,
                            Name = "Colonial Single"
                        },
                        new
                        {
                            Id = 10,
                            AvialableNow = true,
                            BedNumbers = 2,
                            CostId = 5,
                            Description = "Decoración regional y patio interno.",
                            HotelsId = 5,
                            Name = "Tradición Norteña"
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.RoomPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomPictures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "assets/rooms/single-business.jpg",
                            RoomId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "assets/rooms/doble-ejecutiva.jpg",
                            RoomId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "assets/rooms/suite-parana.jpg",
                            RoomId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "assets/rooms/familiar-rosario.jpg",
                            RoomId = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "assets/rooms/suite-malbec.jpg",
                            RoomId = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "assets/rooms/familiar-cordillera.jpg",
                            RoomId = 6
                        },
                        new
                        {
                            Id = 7,
                            Name = "assets/rooms/lago-superior.jpg",
                            RoomId = 7
                        },
                        new
                        {
                            Id = 8,
                            Name = "assets/rooms/suite-nahuel.jpg",
                            RoomId = 8
                        },
                        new
                        {
                            Id = 9,
                            Name = "assets/rooms/colonial-single.jpg",
                            RoomId = 9
                        },
                        new
                        {
                            Id = 10,
                            Name = "assets/rooms/tradicion-nortena.jpg",
                            RoomId = 10
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.TimesAvailable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TimesAvialable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Time = "08:00"
                        },
                        new
                        {
                            Id = 2,
                            Time = "10:00"
                        },
                        new
                        {
                            Id = 3,
                            Time = "12:00"
                        },
                        new
                        {
                            Id = 4,
                            Time = "14:00"
                        },
                        new
                        {
                            Id = 5,
                            Time = "16:00"
                        },
                        new
                        {
                            Id = 6,
                            Time = "18:00"
                        },
                        new
                        {
                            Id = 7,
                            Time = "20:00"
                        },
                        new
                        {
                            Id = 8,
                            Time = "22:00"
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AccountActivate")
                        .HasColumnType("boolean");

                    b.Property<int?>("AddressId")
                        .HasColumnType("integer");

                    b.Property<string>("CodeArea")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("IdAddress")
                        .HasColumnType("text");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOwnAccount")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("ProviderAccount")
                        .HasColumnType("boolean");

                    b.Property<string>("SecondName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Models.Bookings", b =>
                {
                    b.HasOne("Infrastructure.Models.TimesAvailable", "CheckInTime")
                        .WithMany()
                        .HasForeignKey("CheckInTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("CheckInTime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Models.City", b =>
                {
                    b.HasOne("Infrastructure.Models.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Infrastructure.Models.Hotel", b =>
                {
                    b.HasOne("Infrastructure.Models.Address", "AddressHotel")
                        .WithMany()
                        .HasForeignKey("AddressHotelId");

                    b.HasOne("Infrastructure.Models.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("IdentityNumber")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AddressHotel");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Infrastructure.Models.HotelPicture", b =>
                {
                    b.HasOne("Infrastructure.Models.Hotel", null)
                        .WithMany("HotelPictures")
                        .HasForeignKey("HotelId");
                });

            modelBuilder.Entity("Infrastructure.Models.PreBooking", b =>
                {
                    b.HasOne("Infrastructure.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Models.Province", b =>
                {
                    b.HasOne("Infrastructure.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Infrastructure.Models.Room", b =>
                {
                    b.HasOne("Infrastructure.Models.Cost", "Cost")
                        .WithMany()
                        .HasForeignKey("CostId");

                    b.HasOne("Infrastructure.Models.Hotel", "Hotels")
                        .WithMany()
                        .HasForeignKey("HotelsId");

                    b.Navigation("Cost");

                    b.Navigation("Hotels");
                });

            modelBuilder.Entity("Infrastructure.Models.RoomPicture", b =>
                {
                    b.HasOne("Infrastructure.Models.Room", null)
                        .WithMany("RoomPictures")
                        .HasForeignKey("RoomId");
                });

            modelBuilder.Entity("Infrastructure.Models.User", b =>
                {
                    b.HasOne("Infrastructure.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Infrastructure.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Infrastructure.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Infrastructure.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Models.Hotel", b =>
                {
                    b.Navigation("HotelPictures");
                });

            modelBuilder.Entity("Infrastructure.Models.Room", b =>
                {
                    b.Navigation("RoomPictures");
                });
#pragma warning restore 612, 618
        }
    }
}
